version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=survey
      - DB_NAME=your_database_name
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: survey
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
