name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ensure this matches your Python version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}  # Use PythonAnywhere API token
      run: |
        source venv/bin/activate
        pa_username="ajay04"
        project_name="survey"

        echo "Deploying to PythonAnywhere"
        echo "API Token: ${PA_API_TOKEN:0:4}********"  # Partial token echo for security
        echo "Deploying to: https://www.pythonanywhere.com/user/$pa_username/files/home/$pa_username/$project_name/"

        # Create a tar.gz file excluding unnecessary directories
        tar czf project.tar.gz --exclude='venv' --exclude='.git' --exclude='.github' *

        # Upload the tar.gz file to PythonAnywhere with the token in the header
        curl -F "file=@project.tar.gz" \
            -H "Authorization: Token $PA_API_TOKEN" \
            "https://www.pythonanywhere.com/api/v0/user/$pa_username/files/path/home/$pa_username/$project_name/project.tar.gz"

        # Extract the tar.gz file on PythonAnywhere with the token in the header
        curl -X POST \
            -H "Authorization: Token $PA_API_TOKEN" \
            "https://www.pythonanywhere.com/api/v0/user/$pa_username/files/path/home/$pa_username/$project_name/" \
            --data "path=/home/$pa_username/$project_name/&format=json&extract=true&remove_source=true"

        # Trigger a reload of your web app on PythonAnywhere with the token in the header
        curl -X POST \
            -H "Authorization: Token $PA_API_TOKEN" \
            "https://www.pythonanywhere.com/api/v0/user/$pa_username/webapps/$pa_username.pythonanywhere.com/reload/" \
            --data ""
